Adding Slidebar For team Members Info In About Us Section
Algo-Phantoms/Algo-Phantoms-Frontend pull request #137
Opened 2021-03-13 09:54 UTC by Mrinal81

Hi, I have added the slidebar for team member info in about session. Please review the changes that i have done.
Thank you.

2021-03-13 10:02 UTC, Mrinal81 commented
@Shruti3004  I made a pull request. KIndly review my pull request.

2021-03-31 09:29 UTC, harikesh409 requested changes
Pull the latest changes from master and merge your code.

2021-03-31 09:29 UTC, harikesh409 commented on css/style.css
> +
remove unnecessary blank lines.

2021-03-31 09:29 UTC, harikesh409 commented on index.html
> +    <section id="about" class="about" style="background-color: 		#A9A9A9;">
change the background color it is not in sync with the websites color scheme and add the property in the style.css file and not inline.

2021-03-31 09:29 UTC, harikesh409 commented on index.html
> +             <h1 class="text-center">About Us</h1>
The heading should be Team and shouldn't be a part of the carousel.

2021-03-31 09:29 UTC, harikesh409 commented on index.html
> +    <section id="about" class="about" style="background-color: 		#A9A9A9;">
Instead of merging with the about section create a new section that says team and use that. Leave the about us section as it is.

2021-04-01 18:51 UTC, Mrinal81 commented
@harikesh409  I have made the changes as you asked can you please review it. I am attaching the image as well as video of it. I have doubt  about background color in Team section so could you see that image also.....
![Screenshot from 2021-04-01 23-47-08](https://user-images.githubusercontent.com/76482022/113340035-032b5800-9349-11eb-959f-f56aff4452ab.png)
![Screenshot from 2021-04-01 23-48-13](https://user-images.githubusercontent.com/76482022/113340045-06264880-9349-11eb-85f6-2cebf48bbe6b.png)
![Screenshot from 2021-04-01 23-47-24](https://user-images.githubusercontent.com/76482022/113340125-1b9b7280-9349-11eb-8fd4-ebbd39b2842b.png)

https://user-images.githubusercontent.com/76482022/113340214-353cba00-9349-11eb-93b3-8dcb9d82eaaf.mp4

2021-04-02 04:50 UTC, harikesh409 requested changes
Code for changes present in Screenshots are there. Did you push the changes to this PR only? And also the code is not in sync with the master branch kindly pull the latest changes.

2021-04-02 06:05 UTC, Mrinal81 commented
@harikesh409 Done with all the changes. Please have a look 
 If everything is ok then please add GSSOC21 and Level  Tag....

2021-04-02 06:11 UTC, harikesh409 approved these changes

2021-04-02 06:15 UTC, harikesh409 commented
> @harikesh409 Done with all the changes. Please have a look
> If everything is ok then please add GSSOC21 and Level Tag....

Code looks good but the footer is not sync with the main branch kindly pull and merge.

2021-04-02 06:17 UTC, Mrinal81 commented
@harikesh409 ok

2021-04-02 11:19 UTC, Mrinal81 commented
@harikesh409 How i can sync footer with main branch... can you tell me because i don't no such things i am new on github...

2021-04-02 12:27 UTC, Mrinal81 commented
@harikesh409 please check once..

2021-04-02 13:45 UTC, harikesh409 commented
> @harikesh409 please check once..

Looks good lets wait for @ravikr126 review.

2021-04-02 14:03 UTC, ravikr126 approved these changes
Good everything is good

2021-04-02 14:04 UTC, ravikr126 approved these changes

2021-04-02 14:04 UTC, merged