Addfeature
Algo-Phantoms/Algo-Phantoms-Frontend pull request #195
Opened 2021-03-17 16:38 UTC by Krishan-2000

Issue resolved #115  

Bug in Team page contact -us section email validation is not working.

2021-03-19 03:31 UTC, Krishan-2000 commented
@ravikr126  Sir, I raised my PR can you please review it.

2021-03-22 04:31 UTC, Krishan-2000 commented
@harikesh409 I have raised the pr 5 days ago please review it.

2021-03-22 07:56 UTC, harikesh409 requested changes

2021-03-22 07:56 UTC, harikesh409 commented on team.html
> +                        <a class="nav-link  font-weight-bold nav-items" href="team.html">Team</a>
`#team` is correct only as we are already on the team.html page itself.

2021-03-22 12:14 UTC, Krishan-2000 commented
@harikesh409 Sir I have Updated team.html.

2021-03-22 14:35 UTC, harikesh409 approved these changes

2021-03-23 05:47 UTC, merged