404-page added
Algo-Phantoms/Algo-Phantoms-Frontend pull request #212
Opened 2021-03-19 08:48 UTC by surbhi594

I have fixed the issue-166

2021-03-19 17:34 UTC, harikesh409 requested changes
Github 404 pages should be present in the root folder itself.

Ref: https://help.github.com/articles/custom-404-pages

2021-03-19 17:34 UTC, harikesh409 commented on index.html
> +          <a href="https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend" target="blank" class="entypo-github"><span>Github</span></a>
The `target` attribute value is wrong it should be `_blank`.

2021-03-19 17:34 UTC, harikesh409 commented on 404_page/404_p.html
> +          <a style="text-decoration: none;" class="main-btn" href="https://algo-phantoms.github.io/Algo-Phantoms-Frontend/#" role="button">GO BACK HOME</a>
In `href` instead of giving a static home page url point to `index.html`

2021-03-23 06:33 UTC, harikesh409 commented
@surbhi594 are you working on the changes?

2021-03-23 06:51 UTC, surbhi594 commented
Yes sir. It will be done by tomorrow

2021-03-24 06:08 UTC, harikesh409 commented
Closing it as a new PR #232 is raised.

2021-03-24 06:08 UTC, closed without merging