Modified the button on DSA page
Algo-Phantoms/Algo-Phantoms-Frontend pull request #224
Opened 2021-03-21 14:12 UTC by cryptofox17

# Description

I have removed the script tag for the button on DSA.html page and instead added hyperlink to index.html page. Since someone is designing the entire page I had only modified the button slightly (which I can revert back to the original if required)
Fixes #213 

## List any dependencies that are required for this change 
 NA
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
   
![Screenshot (90)](https://user-images.githubusercontent.com/64403591/111907885-228ad100-8a7d-11eb-8dd5-8fecf4dc1263.png)

    - After :
    
![Screenshot (89)](https://user-images.githubusercontent.com/64403591/111907893-2ae30c00-8a7d-11eb-9c27-f6479a9637b4.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-22 09:12 UTC, harikesh409 requested changes

2021-03-22 09:12 UTC, harikesh409 commented on DSA.html
> +            color: #fff;
As per our discussion in #213 you only need to change the hyperlink so don't change these styles.

2021-03-22 09:12 UTC, harikesh409 commented on DSA.html
> +    <button class="button1" onclick="javascript:location.href = 'index.html';">Go Back</button>
Instead of executing a javascript simply use an anchor tag.

2021-03-22 10:10 UTC, cryptofox17 commented
@harikesh409 I have made the required changes

2021-03-22 16:28 UTC, ravikr126 commented
HII @cryptofox17 CAN YOU MAKE THIS ROADMAP CENTER ALIGN. IT WILL LOOK DECENT AND TITLE  ON THE TOP ON THE ROADMAP AS  "DSA ROADMAP" align it at the center and make button at right bottom of the DSA sheet

2021-03-22 16:42 UTC, cryptofox17 commented
@ravikr126 Actually another person is working on redesigning the entire page, which is also why I have been told not to make any changes to the design.  I only had to remove script tag and instead add an anchor tag which I have done

2021-03-24 10:34 UTC, harikesh409 approved these changes

2021-03-28 15:30 UTC, merged