issue #13 Fixed:"Back to top" button should not be displayed when we …
Algo-Phantoms/Algo-Phantoms-Frontend pull request #235
Opened 2021-03-23 20:48 UTC by shitesh2607

# Description
 "Back to top" button should not be displayed when we are already at top.
 Fixes #13

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before : 
![106865622-71f58780-66f1-11eb-9211-7e34eb16e4cb](https://user-images.githubusercontent.com/72928430/112215970-ff138200-8c46-11eb-9cef-d2e234560de7.png)

    - After :
Uploading Algo Phantoms - Google Chrome 2021-03-24 01-49-49_Trim.mp4…

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-28 15:26 UTC, harikesh409 requested changes

2021-03-28 15:26 UTC, harikesh409 commented on css/style.css
> +    scroll-behavior: smooth;
It is already present for `*` property so adding again is just a repetition.

2021-03-28 15:26 UTC, harikesh409 commented on js/index.js
> +con
remove unnecessary line.

2021-03-28 15:34 UTC, shitesh2607 commented
sure

2021-03-28 18:36 UTC, shitesh2607 commented
Hi @harikesh409 I have updated as per requested changes. So now review it that I can close I this issue.

2021-03-29 07:24 UTC, harikesh409 approved these changes

2021-03-29 07:25 UTC, merged