Contact Form
Algo-Phantoms/Algo-Phantoms-Frontend pull request #272
Opened 2021-03-27 19:34 UTC by padmajabhol

I added a contact form as the issue demanded.

Please include a summary of the change and which issue is fixed.
Fixes #51 

## List any dependencies that are required for this change 
none

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
![Screenshot (61)](https://user-images.githubusercontent.com/75530516/112732689-79067c80-8f61-11eb-813d-637c56dee78e.png)

    - After :
![Screenshot (60)](https://user-images.githubusercontent.com/75530516/112732694-7dcb3080-8f61-11eb-8bd0-ed4a63ebde60.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-28 14:51 UTC, harikesh409 requested changes
Also make the same changes in `team.html`

2021-03-28 14:51 UTC, harikesh409 commented on css/style.css
> +
remove the blank line.

2021-03-28 14:51 UTC, harikesh409 commented on index.html
> +                        <!-- <div class="input-group">
You can remove the unnecessary code no need to keep comments.

[Yagni](https://martinfowler.com/bliki/Yagni.html)

2021-03-28 14:51 UTC, harikesh409 commented on index.html
> +                        <input type="text" class="form-control py-3" placeholder="Your Name">
Refer [bootstrap forms](https://getbootstrap.com/docs/4.3/components/forms/) and the forms  divs using `form-group` classes. Also give some margins it looks a bit tight as there is no space between the container background and input fields.

2021-03-28 16:01 UTC, padmajabhol commented
> Also make the same changes in `team.html`

Sure

2021-03-28 18:03 UTC, padmajabhol commented
@harikesh409 Please review the changes of the latest commit Contactform.

2021-03-30 12:42 UTC, Khushi-agarwal commented
@harikesh409 can I work on this issue?

2021-03-30 15:03 UTC, harikesh409 requested changes

2021-03-30 15:03 UTC, harikesh409 commented on team.html
> +                        </div>
unnecessary closing div tag.

2021-03-30 15:03 UTC, harikesh409 commented on team.html
> +                        <a class="text-white mb-lg-3" href="#about">About</a><br>
The link should be `index.html#about`

2021-03-30 15:04 UTC, harikesh409 commented
> @harikesh409 can I work on this issue?

Already the issue is being worked by @padmajabhol, so choose some other issue.

2021-03-30 17:32 UTC, harikesh409 approved these changes

2021-03-31 06:34 UTC, harikesh409 commented
moved to #300

2021-03-31 06:34 UTC, closed without merging