Project Ideas dropdown section added
Algo-Phantoms/Algo-Phantoms-Frontend pull request #280
Opened 2021-03-28 18:32 UTC by gayatri517

# Description
I have added a project ideas section in the more section of the navbar, where a link to a website is provided listing various project ideas.
Issue #220 

## List any dependencies that are required for this change 
None

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have verified the link attached. It is working perfectly.

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before : 
![before](https://user-images.githubusercontent.com/70585276/112763273-6d7a8a80-9021-11eb-9b58-5f952a5a47ea.png)

    - After : 
![project Idea](https://user-images.githubusercontent.com/70585276/112763294-78cdb600-9021-11eb-93b1-d5d45d1f8242.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-28 18:33 UTC, gayatri517 commented
@harikesh409 Kindly review the PR.
Thank you.

2021-03-31 05:06 UTC, gayatri517 commented
@harikesh409 kindly review my PR.
Thank you

2021-03-31 08:27 UTC, harikesh409 requested changes
As it is an external website instead of adding in the navbar add it in the Features section in footer.

2021-03-31 11:08 UTC, gayatri517 commented
@harikesh409 I have made the changes. Kindly review it.
Thank you.

2021-03-31 15:04 UTC, harikesh409 requested changes

2021-03-31 15:04 UTC, harikesh409 commented on index.html
> +
Remove blank line.

2021-03-31 18:04 UTC, gayatri517 commented
@harikesh409 I have made the changes. Kindly review.
Thank you

2021-04-02 07:24 UTC, harikesh409 approved these changes

2021-04-02 07:26 UTC, harikesh409 requested changes
As it is an external link instead of keeping it in the navbar move that to the footer under `Features` section.

2021-04-02 11:34 UTC, gayatri517 commented
@harikesh409 I have changed the link from the navbar to the footer section
![pic1](https://user-images.githubusercontent.com/70585276/113412248-6b278000-93d5-11eb-998a-2cd8c67d910d.png)
![pic2](https://user-images.githubusercontent.com/70585276/113412257-6fec3400-93d5-11eb-83a5-185472e5d25c.png)

2021-04-02 13:44 UTC, harikesh409 commented
> @harikesh409 I have changed the link from the navbar to the footer section
> ![pic1](https://user-images.githubusercontent.com/70585276/113412248-6b278000-93d5-11eb-998a-2cd8c67d910d.png)
> ![pic2](https://user-images.githubusercontent.com/70585276/113412257-6fec3400-93d5-11eb-83a5-185472e5d25c.png)

Push your commits. @gayatri517

2021-04-02 17:39 UTC, gayatri517 commented
@harikesh409 I have done the changes. Kindly review now.
Thanks

2021-04-03 15:03 UTC, merged