Made changes in the Team Cards UI
Algo-Phantoms/Algo-Phantoms-Frontend pull request #285
Opened 2021-03-29 15:27 UTC by harshb02

# Description

Changed the color of the name and description of the team members and added some styles. Also added a hover effect on the social icons.
Fixes #279

## List any dependencies that are required for this change 
NA

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Ran on local server
## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
   
![screencapture-file-C-Users-HARSH-Downloads-Algo-Phantoms-Frontend-master-2-Algo-Phantoms-Frontend-master-team-html-2021-03-29-20_49_22](https://user-images.githubusercontent.com/58955446/112859589-9ad24180-90d0-11eb-8b91-22b114559143.png)

    - After :
    - 
![screencapture-file-C-Users-HARSH-Desktop-AlgoPhantom-Algo-Phantoms-Frontend-team-html-2021-03-29-20_49_33](https://user-images.githubusercontent.com/58955446/112859671-ad4c7b00-90d0-11eb-83a8-d6f23d9de7ed.png)

![demo](https://user-images.githubusercontent.com/58955446/112859742-c2290e80-90d0-11eb-8825-6fb130e8001e.gif)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-03-29 15:43 UTC, harikesh409 requested changes

2021-03-29 15:43 UTC, harikesh409 commented on css/style.css
> +    color: white;
Use hex color.

2021-03-29 15:43 UTC, harikesh409 commented on css/style.css
> +
Remove the unnecessary empty lines.

2021-03-31 09:20 UTC, harikesh409 requested changes
![image](https://user-images.githubusercontent.com/3501554/113121514-5e1d5c00-9230-11eb-97df-fa3c21d9d96d.png)
The name **MANSHI TODI** is no visible properly due the color. So just move that circle background a bit top so that the name is visible.

2021-03-31 15:39 UTC, harshb02 commented
> ![image](https://user-images.githubusercontent.com/3501554/113121514-5e1d5c00-9230-11eb-97df-fa3c21d9d96d.png)
> The name **MANSHI TODI** is no visible properly due the color. So just move that circle background a bit top so that the name is visible.

The changes have been made kindly review them @harikesh409

2021-04-02 15:18 UTC, harshb02 commented
We both have made changes in the teams page and have merged our ideas. She has already made a PR of the changes she has done (issue #314). Kindly review the changes @harikesh409

2021-04-02 15:39 UTC, Khushi-agarwal commented
@harikesh409  we have made the changes as requested by you in the pr which I created that is pr #314 and all the changes have been added here. So kindly review it.

2021-04-02 15:40 UTC, Khushi-agarwal commented
Also @harikesh409  this pr is not assigned to me. So please assign it to me as well.

2021-04-03 14:14 UTC, ravikr126 approved these changes

2021-04-03 14:25 UTC, Khushi-agarwal commented
@ravikr126 please assign this pr to me as well as I have also made the changes.

2021-04-03 14:36 UTC, harikesh409 requested changes
All changes are looking good but the `team.html` page is not upto date with the master branch check the navbar few options are missing kindly pull code from master and merge your changes then we can merge the branch.

2021-04-03 15:09 UTC, harshb02 commented
I have updated the team.html page kindly check @harikesh409 @Khushi-agarwal

2021-04-03 18:02 UTC, merged