SiteMap.html  Enhancement
Algo-Phantoms/Algo-Phantoms-Frontend pull request #290
Opened 2021-03-30 07:56 UTC by tier3guy

issue : #278

In this PR I made some changes in UI and as the major issue was that the arrows were not aligned properly , so I fixed that . Please do consider my PR.

After changes : 
![2021-03-30](https://user-images.githubusercontent.com/73595465/112953947-8edf9180-915b-11eb-850b-debe1de32b08.png)

2021-03-30 18:29 UTC, harikesh409 requested changes

2021-03-30 18:29 UTC, harikesh409 commented on css/sitemapStyles.css
> +    background:#000000;
Don't use black background it is never recommended. Choose the existing color scheme.

2021-03-30 18:29 UTC, harikesh409 commented on css/sitemapStyles.css
> +
Remove unnecessary blank lines.

2021-03-30 18:29 UTC, harikesh409 commented on sitemap.html
> +			<div class="links">
Use proper indentations.

2021-03-30 18:29 UTC, harikesh409 commented on sitemap.html
> +					<a href="https://github.com/Algo-Phantoms/Algo-Tree">DSA Guidance</a>
Instead of pointing to the github repo point to the `DSA.html`.

2021-04-01 10:16 UTC, tier3guy commented
@harikesh409 sir , I have already made changes but in my sitemap branch the changes are implemented successfully but not in the master branch even after the merging

2021-04-02 06:52 UTC, harikesh409 commented
Moved to #310

2021-04-02 06:52 UTC, closed without merging