Issue.104
Algo-Phantoms/Algo-Phantoms-Frontend pull request #303
Opened 2021-03-31 10:34 UTC by neha-baisane

This is  new pull request for issue.104. Made all the changes @harikesh409 Please review.

2021-03-31 14:57 UTC, harikesh409 requested changes

2021-03-31 14:57 UTC, harikesh409 commented on css/style.css
> +center {
`center` tag by default provides centering so no need to give margin left and margin right auto.

2021-03-31 14:57 UTC, harikesh409 commented on index.html
> +<section id="sharpen-skills" class="section">
Make the class name `skills-section`.

2021-03-31 14:57 UTC, harikesh409 commented on css/style.css
> +.section table{
In similar way change other tags also not only table.

- th
- tr
- td
- a
- hr
- h1

2021-03-31 14:57 UTC, harikesh409 commented on css/style.css
> +   color:#000000;
If the color is same in all states then no need to specify it individually.

2021-03-31 15:34 UTC, neha-baisane commented
@harikesh409 Done with all the changes . Please have a look.

2021-03-31 15:40 UTC, harikesh409 approved these changes

2021-04-02 07:02 UTC, neha-baisane commented
@ravikr126 @harikesh409  Done from my side and if everything is fine please merge my PR.

2021-04-02 14:07 UTC, ravikr126 commented
Please remove conflict then we review and merge it @neha-baisane

2021-04-02 14:51 UTC, neha-baisane commented
@ravikr126 Please guide me how to resolve this conflict.

2021-04-02 14:53 UTC, ravikr126 commented
You need to pull new code and make change on it .Some one already changes same line that you edited.

You can read this also
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-merge-conflicts#:~:text=If%20your%20merge%20conflict%20is,GitHub%20using%20the%20conflict%20editor.&text=push%20the%20change.-,For%20more%20information%2C%20see%20%22Resolving%20a%20merge,conflict%20on%20the%20command%20line.%22

2021-04-02 15:41 UTC, neha-baisane commented
@ravikr126 resolved the conflicts . Please review.

2021-04-03 07:03 UTC, neha-baisane commented
@ravikr126 resolved the conflicts . Please review.

2021-04-03 07:04 UTC, ravikr126 commented
Then create new pr request

2021-04-03 14:44 UTC, harikesh409 commented
Moved to #322

2021-04-03 14:44 UTC, closed without merging