BookList #Issue222 New pr
Algo-Phantoms/Algo-Phantoms-Frontend pull request #306
Opened 2021-03-31 16:51 UTC by sohini3062

# Description
New pr for adding suggested booklist webpage under More on the navigation bar using HTML and CSS. 
Please include a summary of the change and which issue is fixed.
Fixes # (issue)
#222 
## List any dependencies that are required for this change 
The old pr number is
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
    - After :
## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-03-31 16:53 UTC, sohini3062 commented
@harikesh409 The new Pr in reference to https://github.com/Algo-Phantoms/Algo-Phantoms-Frontend/pull/223

2021-04-02 07:39 UTC, harikesh409 commented
@sohini3062 resolve the conflicts and #208 is present which can be resolved.

2021-04-02 08:08 UTC, sohini3062 commented
Ok I am working on it

2021-04-02 08:48 UTC, sohini3062 commented
Resolved Conflicts.
Issue #208 fixed
**Before:**
![before](https://user-images.githubusercontent.com/64258756/113399632-26441f00-93be-11eb-8d12-de8c04b74c9b.jpeg)
**After:**
![after2](https://user-images.githubusercontent.com/64258756/113399653-2d6b2d00-93be-11eb-8799-a2ea5e7cd69e.jpeg)
![after1](https://user-images.githubusercontent.com/64258756/113399672-33f9a480-93be-11eb-8c16-0d545ae5933b.jpeg)

2021-04-02 13:50 UTC, harikesh409 requested changes

2021-04-02 13:50 UTC, harikesh409 commented on index.html
> +                            <a class="dropdown-item" href="practicedsa.html">DSA Problems</a> master
what is this additional master?

2021-04-02 13:50 UTC, harikesh409 commented on css/bookliststyle.css
> +  /* background-image:linear-gradient(130deg, #ffa159 10%, #ff39b4 51%, #ffa159 100%);    */
Remove the comment if not using.

2021-04-02 15:03 UTC, sohini3062 commented on css/bookliststyle.css
> +  /* background-image:linear-gradient(130deg, #ffa159 10%, #ff39b4 51%, #ffa159 100%);    */
Ok done

2021-04-03 15:04 UTC, harikesh409 commented
@sohini3062 resolve conflicts.

2021-04-05 04:51 UTC, sohini3062 commented
i have resolved the conflicts.

2021-04-05 16:52 UTC, harikesh409 approved these changes

2021-04-06 13:51 UTC, sohini3062 commented
Is there anything else to be added ?

2021-04-06 17:21 UTC, ravikr126 approved these changes

2021-04-06 17:21 UTC, merged