Aligned the contents of the navbar to the center
Algo-Phantoms/Algo-Phantoms-Frontend pull request #335
Opened 2021-04-03 20:06 UTC by 123mansha

# Description

Please include a summary of the change and which issue is fixed.
- Aligned the contents of the navbar in the center.
- Changed the transparent background to solid background 
Fixes # 309

## List any dependencies that are required for this change 
no dependencies

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
![Screenshot (9)](https://user-images.githubusercontent.com/59260493/113489915-98168880-94e4-11eb-9288-d2b1dd9e1c1b.png)

    - After :

![Screenshot (12)](https://user-images.githubusercontent.com/59260493/113490086-a2855200-94e5-11eb-9f6d-cb08f3646170.png)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-04 08:28 UTC, ravikr126 approved these changes

2021-04-04 14:49 UTC, harikesh409 requested changes
![image](https://user-images.githubusercontent.com/3501554/113512600-0742ba00-9583-11eb-9411-313012513bc7.png)
The content under the more is aligned to left it looks better if it is also aligned to center.

2021-04-04 14:49 UTC, harikesh409 commented on css/style.css
> +  /*opacity: 0.8;*/
Remove comment if not needed.

2021-04-04 14:49 UTC, harikesh409 commented on css/style.css
> +/*.top {
Remove comment if not needed.

2021-04-04 14:49 UTC, harikesh409 commented on css/style.css
> +  /*text-align: right;*/
Remove comment if not needed.

2021-04-06 06:31 UTC, 123mansha commented
Okk, I will do

2021-04-08 08:16 UTC, ravikr126 approved these changes

2021-04-08 08:16 UTC, merged