background color changed
Algo-Phantoms/Algo-Phantoms-Frontend pull request #338
Opened 2021-04-04 13:44 UTC by tier3guy

fixes : #278
![2021-04-03](https://user-images.githubusercontent.com/73595465/113510780-ff324c80-9579-11eb-8b25-920893518a37.png)

2021-04-04 14:33 UTC, harikesh409 requested changes

2021-04-04 14:33 UTC, harikesh409 commented on sitemap.html
> +		<div class="footer">Copyright &copy; 2021 <a href="#" style="color: #3caea3; text-decoration: none;" target="_blank"><span class="font-weight-bold">AlgoPhantoms.</span></a> All Rights Reserved</div
Instead of inline styles use the stylesheet.

2021-04-04 14:33 UTC, harikesh409 commented on sitemap.html
> +		<div class="footer">Copyright &copy; 2021 <a href="#" style="color: #3caea3; text-decoration: none;" target="_blank"><span class="font-weight-bold">AlgoPhantoms.</span></a> All Rights Reserved</div
Point the link to `index.html`.

2021-04-04 14:33 UTC, harikesh409 commented on sitemap.html
> +						<a href="https://www.codechef.com/ide">Code Editor</a>
No need to keep third party links in the sitemap file.

2021-04-14 16:06 UTC, harikesh409 commented
@tier3guy are the changes done?

2021-04-14 16:14 UTC, tier3guy commented
Sorry sir , I am on the bed for around 10days as I am tested positive , give me one more day , I will raise the PR for the same .
Request 🙏

2021-04-14 16:29 UTC, tier3guy commented
Sir give me one more day , PLZZ , I am raising the PR by tomorrow .

2021-04-24 10:17 UTC, harikesh409 commented
> Sir give me one more day , PLZZ , I am raising the PR by tomorrow .

Any progress, if not I will assign it to somebody else.

2025-09-25 15:48 UTC, closed without merging