Added FAQ section
Algo-Phantoms/Algo-Phantoms-Frontend pull request #339
Opened 2021-04-04 14:42 UTC by harshb02

# Description
Added a FAQ section in the index.html. I have written dummy text for now which will be replaced by the content as soon I get it.

Fixes #326 

## List any dependencies that are required for this change 
NA

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Ran on local server

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
<img width="960" alt="2" src="https://user-images.githubusercontent.com/58955446/113512218-32c4a500-9581-11eb-8d8b-a2f27207ffff.png">

    - After :
    
<img width="960" alt="1" src="https://user-images.githubusercontent.com/58955446/113512226-3eb06700-9581-11eb-886a-d9bda1e959d1.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/58955446/113512230-42dc8480-9581-11eb-81c1-b284b8b6daaf.png">

![demo6](https://user-images.githubusercontent.com/58955446/113512320-b8485500-9581-11eb-9872-d2bebf0c658b.gif)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-04 15:51 UTC, harikesh409 requested changes

2021-04-04 15:51 UTC, harikesh409 commented on index.html
> +           <div class="accordion" id="accordionExample">
Make the id more meaningful

2021-04-04 15:51 UTC, harikesh409 commented on index.html
> +    <div class="row row-content">
`row-content` is unnecessary tag.

2021-04-04 15:51 UTC, harikesh409 commented on index.html
> +        <h1 class="text-center">FREQUENTLY ASKED QUESTIONS</h1>
Make it init caps instead of all caps.

2021-04-04 15:51 UTC, harikesh409 commented on index.html
> +        <h1 class="text-center">FREQUENTLY ASKED QUESTIONS</h1>
Add other styles also which are present for other headings.

2021-04-04 15:51 UTC, harikesh409 commented on css/style.css
> +    text-transform: uppercase;
Transforming to uppercase is not needed.

2021-04-04 15:51 UTC, harikesh409 commented on css/style.css
> +    padding: .75rem 1.25rem;
Except `box-shadow` rest all are default properties that comes from bootstrap itself so they can be removed.

2021-04-04 15:51 UTC, harikesh409 commented on index.html
> +                <i class="fas fa-plus"></i>  Services we provide you
Just a suggestion.
It looks good if the plus changes to minus on click.

2021-04-04 15:51 UTC, harikesh409 commented on index.html
> +            </div>
Maintain proper indentations.

2021-04-04 17:16 UTC, harshb02 commented
I have made the changes kindly review them @harikesh409

2021-04-05 16:48 UTC, harikesh409 requested changes

2021-04-05 16:48 UTC, harikesh409 commented on index.html
> +<div class="fnq" id="fnq">
`section` is a more preferable tag for SEO.

2021-04-05 16:48 UTC, harikesh409 commented on index.html
>      <div class="container mt-5 mb-5">
Instead of two classes mt-5 and mb-5 you can use my-5

2021-04-05 16:48 UTC, harikesh409 commented on index.html
> +</div>
Check indentations.

2021-04-05 17:19 UTC, harshb02 commented
Implemented the changes. Kindly review them @harikesh409

2021-04-05 17:19 UTC, harikesh409 approved these changes

2021-04-06 04:46 UTC, ravikr126 approved these changes
Done

2021-04-06 04:46 UTC, merged