Added navbar in booklist.html
Algo-Phantoms/Algo-Phantoms-Frontend pull request #384
Opened 2021-04-10 18:55 UTC by kanishka8276

# Description
Added navbar in booklist.html and did styling of the list of books. Also linked about under useful links correctly.
Fixes # (issue)
#371
## List any dependencies that are required for this change 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

![Screenshot (238)](https://user-images.githubusercontent.com/66053534/114281525-76754e00-9a5c-11eb-993b-72069d3ca7ed.png)

2021-04-13 17:32 UTC, ravikr126 approved these changes

2021-04-13 17:45 UTC, ravikr126 requested changes
add books pdfs

2021-04-24 11:29 UTC, harikesh409 requested changes

2021-04-24 11:29 UTC, harikesh409 commented on booklist.html
> +            const navbar=document.getElementById("nav");
Add the `nav` id to the nav tag.

2021-04-24 11:29 UTC, harikesh409 commented on booklist.html
> +                    navbar.classList.remove("top");
Include the `top` class to the navbar.

2021-04-24 11:29 UTC, harikesh409 commented on booklist.html
> +    <center>
`<center>` tag is deprecated so don't use it.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

2021-04-24 14:39 UTC, kanishka8276 commented
@harikesh409 Made the suggested changes. Please review.
![Screenshot (253)](https://user-images.githubusercontent.com/66053534/115962418-ed204a00-a538-11eb-9994-90a83195f0e2.png)

2021-04-24 15:07 UTC, harikesh409 requested changes
Also the social icons style in follow us of footer is different from home page change those also to the style as it is present in the home page.

2021-04-24 16:41 UTC, harikesh409 approved these changes

2021-04-25 04:58 UTC, ravikr126 commented
wait for some more time when pa give their drive access i will give you the links of pdf and then you add then we merge this PR.
@kanishka8276

2021-05-09 13:27 UTC, kanishka8276 commented
@ravikr126 Please merge this PR. I can create another PR for adding books as otherwise I will have to keep on resolving the conflicts.

2021-05-09 13:46 UTC, harikesh409 commented
> @ravikr126 Please merge this PR. I can create another PR for adding books as otherwise I will have to keep on resolving the conflicts.

Merge markers are present in the files remove those and push then I can merge it.

2021-05-09 15:11 UTC, ravikr126 commented
@kanishka8276

2021-05-09 15:15 UTC, kanishka8276 commented
@harikesh409 @ravikr126 Done!

2021-05-09 15:16 UTC, merged