added id to the navbar
Algo-Phantoms/Algo-Phantoms-Frontend pull request #398
Opened 2021-04-14 05:53 UTC by tanishq-arya

# Description

Please include a summary of the change and which issue is fixed.
Fixes #397 

## List any dependencies that are required for this change 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
    - After :
## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

![image](https://user-images.githubusercontent.com/77333275/114660936-c3cf1500-9d13-11eb-82f7-a69684c0f781.png)

2021-04-24 10:51 UTC, harikesh409 requested changes
Add the same id in other pages also and add 
```css
.top{
    background: transparent;
}
``` in `style.css`

2021-04-24 10:51 UTC, harikesh409 commented on index.html
> +        <nav id="nav" class="navbar navbar-expand-lg navbar-dark fixed-top nav-col">
Add the top class.

2021-04-25 07:38 UTC, tanishq-arya commented
The team.html js error is because of the debugger of the browser and not because of any functionality.

2021-04-25 07:52 UTC, harikesh409 approved these changes

2021-04-25 07:53 UTC, merged