nav bar added
Algo-Phantoms/Algo-Phantoms-Frontend pull request #412
Opened 2021-04-16 06:52 UTC by shonali2600

# Description

Please include a summary of the change and which issue is fixed.
Fixes #378 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
![nav](https://user-images.githubusercontent.com/57946528/114983508-55728a00-9eae-11eb-8c3d-a8898288d3bd.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2021-04-16 06:53 UTC, shonali2600 commented
@ravikr126  please review my PR

2021-04-18 13:45 UTC, ravikr126 approved these changes

2021-04-23 04:30 UTC, shonali2600 commented
@harikesh409 Kindly review my PR, and let me know if any changes to be made.

2021-04-23 04:32 UTC, shonali2600 commented
@ravikr126 This issue is of `Level 2`, and you mistakenly labeled it `level1`, Please resolve this

2021-04-23 08:46 UTC, ravikr126 approved these changes

2021-04-24 08:26 UTC, harikesh409 requested changes
Include bootstrap and jquery js files in both the pages so that the More menu will work.

2021-04-24 08:26 UTC, harikesh409 commented on DSA.html
> +            const navbar=document.getElementById("nav");
Use correct selector or add the id to the nav tag.

2021-04-24 08:26 UTC, harikesh409 commented on DSA.html
> +                    <li class="nav-item active">
Home shouldn't be having the active class as it is not the current page.

2021-04-24 08:26 UTC, harikesh409 commented on DSA.html
> +                    </ul>
Correct the indentation.

2021-04-24 08:26 UTC, harikesh409 commented on practicedsa.html
> +            const navbar=document.getElementById("nav");
Use correct selector or add the id to the nav tag.

2021-04-24 08:26 UTC, harikesh409 commented on practicedsa.html
> +                    </li>
Correct the indentation.

2021-04-24 08:27 UTC, harikesh409 requested changes

2021-04-24 08:27 UTC, harikesh409 commented on practicedsa.html
> +                        <a class="nav-link font-weight-bold nav-items" href="index.html">Home </a>
Home shouldn't be having the active class as it is not the current page.

2021-04-24 09:33 UTC, shonali2600 commented
@harikesh409 , made all the required changes, now please review.

2021-04-24 09:41 UTC, harikesh409 requested changes
Add 
```css
.top{
    background: transparent;
}
``` 
this part in `style.css` which has been missed.
Add `top` class to the `<nav>` which is needed in both files.

2021-04-24 11:32 UTC, shonali2600 commented
Done

2021-04-24 11:35 UTC, harikesh409 requested changes

2021-04-24 11:35 UTC, harikesh409 commented on DSA.html
> +            const navbar = document.getElementsByTagName("nav");
It will give error when accessing `classList` it should be: `document.getElementsByTagName("nav")[0]`

2021-04-24 11:35 UTC, harikesh409 commented on practicedsa.html
> +            const navbar = document.getElementsByTagName("nav");
It will give error when accessing `classList` it should be: `document.getElementsByTagName("nav")[0]`

2021-04-24 14:00 UTC, harikesh409 approved these changes

2021-04-24 14:00 UTC, harikesh409 commented on DSA.html
> +            const navbar = document.getElementsByTagName("nav");
Resolve this also.

2021-04-24 14:04 UTC, merged