Aligned and Improved the Skills section in mobile view
Algo-Phantoms/Algo-Phantoms-Frontend pull request #429
Opened 2021-04-19 15:15 UTC by harshb02

# Description
Aligned and Improved the Skills section in mobile view

Please include a summary of the change and which issue is fixed.
Fixes #391 

## List any dependencies that are required for this change 
NA

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
On my local host

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
   -
![WhatsApp Image 2021-04-19 at 8 32 09 PM](https://user-images.githubusercontent.com/58955446/115260128-195e5400-a150-11eb-9086-8fca2b3dcf9f.jpeg)

    - After :
    
![WhatsApp Image 2021-04-19 at 8 41 23 PM](https://user-images.githubusercontent.com/58955446/115260160-1feccb80-a150-11eb-81ca-dc7470d92cce.jpeg)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-21 13:39 UTC, ravikr126 approved these changes

2021-04-23 08:44 UTC, ravikr126 commented
REMOVE THE MERGE CONFLICTS @harshb02

2021-04-23 17:32 UTC, ravikr126 commented
removes conflicts @harshb02

2021-04-23 17:35 UTC, harshb02 commented
> removes conflicts @harshb02 

Will remove them by tomorrow @ravikr126

2021-04-24 07:11 UTC, harikesh409 requested changes

2021-04-24 07:11 UTC, harikesh409 commented on index.html
> +    <div class="d-none d-lg-block">
Correct the indentation.

2021-04-24 14:47 UTC, harikesh409 requested changes

2021-04-24 14:47 UTC, harikesh409 commented on css/style.css
> -@import url("https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,700;0,900;1,900&display=swap");
Why are the fonts removed? they are still being used in the css file.

2021-04-30 07:28 UTC, closed without merging