Contact Button&Link update
Algo-Phantoms/Algo-Phantoms-Frontend pull request #43
Opened 2021-02-28 17:22 UTC by WaderManasi

Fixed issue of contact link and button by updating with given mail-id.

2021-03-23 05:48 UTC, harikesh409 requested changes

2021-03-23 05:48 UTC, harikesh409 commented on index.html
> +    <link rel="stylesheet" href="./css/style.css">
No need to point the current directory using ./, keep the original `css/style.css` only.

2021-03-23 05:56 UTC, harikesh409 requested changes

2021-03-23 05:56 UTC, harikesh409 commented on index.html
> +                                    <a id="contact_button" href="mailto:algophantom0101@gmail.com">Contact Us</a>
If we use this href method then the form and the input is useless so instead of keeping the mailto here keep it in the form `action` attribute.

2021-03-23 05:56 UTC, harikesh409 commented on index.html
> +                        <a class="text-white mb-lg-3" href="mailto:algophantom0101@gmail.com">Contact</a>
Use the footer only as we are using a form over there.

2021-03-23 05:56 UTC, harikesh409 commented on team.html
> +                                    <a id="contact_button" href="mailto:algophantom0101@gmail.com">Contact Us</a>
Use the form action only.

2021-03-23 05:56 UTC, harikesh409 commented on team.html
> +                        <a class="text-white mb-lg-3" href="mailto:algophantom0101@gmail.com">Contact</a>
Use the footer only on using this the footer contact input will be dead.

2021-03-23 06:56 UTC, WaderManasi commented
Sure..
will make the changes in file as mentioned above.

2021-03-27 15:30 UTC, harikesh409 requested changes

2021-03-27 15:30 UTC, harikesh409 commented on index.html
>                      <form action="">
Keep the mailto action.

2021-03-27 15:31 UTC, WaderManasi commented on index.html
>                      <form action="">
okay

2021-03-28 05:41 UTC, WaderManasi commented
@harikesh409  I have added form action to the required mail-id.

2021-03-28 05:55 UTC, harikesh409 approved these changes

2021-03-29 19:06 UTC, ravikr126 approved these changes

2021-03-29 19:06 UTC, merged