Faq section aligned and styled in mobile view
Algo-Phantoms/Algo-Phantoms-Frontend pull request #430
Opened 2021-04-19 15:25 UTC by harshb02

# Description
Faq section aligned and styled in mobile view

Please include a summary of the change and which issue is fixed.
Fixes #390 

## List any dependencies that are required for this change 
Na

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
On my local host

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
   - 
![WhatsApp Image 2021-04-19 at 8 52 14 PM](https://user-images.githubusercontent.com/58955446/115261702-79a1c580-a151-11eb-8581-df7d6662b9c8.jpeg)

    - After :
    
![WhatsApp Image 2021-04-19 at 8 51 29 PM](https://user-images.githubusercontent.com/58955446/115261732-7f97a680-a151-11eb-90e2-fc03bb3d7f20.jpeg)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-04-23 08:45 UTC, ravikr126 commented
REMOVE MERGE CONFLICTS @harshb02

2021-04-23 09:03 UTC, harshb02 commented
Removed the conflicts @ravikr126

2021-04-23 17:31 UTC, ravikr126 approved these changes

2021-04-24 07:13 UTC, harikesh409 reviewed
Aren't these changes same as #429

2021-04-24 13:57 UTC, harshb02 commented
> Aren't these changes same as #429 

No in #429 I have aligned the Sharpen your Skills sectionin mobile view and in this PR I have aligned the FAQ section in mobile view.

2021-04-24 14:10 UTC, harikesh409 requested changes

2021-04-24 14:10 UTC, harikesh409 commented on index.html
> +    <div class="d-none d-lg-block">
Correct the indentations.

2021-04-24 14:48 UTC, harikesh409 commented
> > Aren't these changes same as #429
> 
> No in #429 I have aligned the Sharpen your Skills sectionin mobile view and in this PR I have aligned the FAQ section in mobile view.

Okay both the changes are present here so I thought they were the same changes anyways do the requested changes we can merge it.

2021-04-24 16:04 UTC, harshb02 commented
I have removed the div because it was for not displaying the social sidebar in the mobile view but eventually it was done by someone else so I have removed the div and have done the changes @harikesh409

2021-04-24 16:43 UTC, harikesh409 commented
> I have removed the div because it was for not displaying the social sidebar in the mobile view but eventually it was done by someone else so I have removed the div and have done the changes @harikesh409

okay resolve the conflicts so that we can merge.

2021-04-27 04:42 UTC, ravikr126 commented
resolve the conflict @harshb02

2021-04-28 11:32 UTC, harshb02 commented
Removed the conflicts @ravikr126  @harikesh409

2021-04-29 17:22 UTC, ravikr126 approved these changes

2021-04-29 17:22 UTC, merged