Added links to skills section and enhanced them
Algo-Phantoms/Algo-Phantoms-Frontend pull request #445
Opened 2021-04-23 13:41 UTC by codebuzzer01

# Description

Links to the specific site of that particular topic is added which lets user redirect to a new page for each skill and logo is enhanced as well.

# Fixes # (427)

## List any dependencies that are required for this change  
No

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? 

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
![Screenshot (217)](https://user-images.githubusercontent.com/52864294/115878996-cc87bf80-a466-11eb-94c4-2cd6cc027923.png)
![Screenshot (218)](https://user-images.githubusercontent.com/52864294/115879011-ceea1980-a466-11eb-8e55-c2b077142891.png)
   - After :
![Screenshot (219)](https://user-images.githubusercontent.com/52864294/115879070-e0332600-a466-11eb-84a0-71ed9e0d9698.png)
Required skill gets open in new tab:
![Screenshot (220)](https://user-images.githubusercontent.com/52864294/115879079-e2958000-a466-11eb-93a8-4c85b8375b70.png)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2021-04-23 13:43 UTC, codebuzzer01 commented
@ravikr126  I have resolved the above issue. Kindly review it.

2021-04-23 13:51 UTC, ravikr126 approved these changes

2021-04-23 13:57 UTC, codebuzzer01 commented
@harikesh409  I have resolved the above issue. Kindly review it.

2021-04-24 08:04 UTC, harikesh409 requested changes

2021-04-24 08:04 UTC, harikesh409 commented on index.html
> +        <th><i class="devicon-cplusplus-line-wordmark fa-lg"></i>&nbsp; <a href="https://www.youtube.com/watch?v=g-1Cn3ccwXY" target="_blank">STL</a></th>
STL is a part of CPP only so revert it back to Ruby only if you are unable to find any correct resources you can ask us or leave it blank.

2021-04-24 08:04 UTC, harikesh409 commented on index.html
> +        <th><i class="devicon-devicon-plain"></i>&nbsp; <a href="https://clist.by/" target="_blank">Contests</a></th>
Contents is not a skill so revert back to mathematics only.

2021-04-24 08:04 UTC, harikesh409 commented on index.html
> +        <th><i class="devicon-redhat-plain"></i>&nbsp; <a href="https://devpost.com/hackathons" target="_blank">Hackathons</a></th>
Hackathons is not a skill you can change to Databases or SQL.

2021-04-24 08:04 UTC, harikesh409 commented on index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.11.0/devicon.min.css">
Don't include additional icon packs kindly remove them and use the existing packs only.

2021-04-24 08:18 UTC, codebuzzer01 commented
Ok @harikesh409  I will do the requested changes.

2021-04-24 08:37 UTC, codebuzzer01 commented
@harikesh409 

![Screenshot (223)](https://user-images.githubusercontent.com/52864294/115952893-5a66b780-a506-11eb-8f88-13d93d3ecbee.png)

2021-04-24 08:48 UTC, codebuzzer01 commented
@harikesh409  tell me if it's okay?

2021-04-24 09:24 UTC, harikesh409 requested changes

2021-04-24 09:24 UTC, harikesh409 commented on index.html
> +        <th><i class="devicon-ruby-plain"></i>&nbsp; <a href="https://www.youtube.com/watch?v=t_ispmWmdjY" target="_blank">Ruby</a></th>
Font awesome gem icon can be used here.

2021-04-24 09:24 UTC, harikesh409 commented on index.html
> +        <th><i class="devicon-swift-plain"></i>&nbsp; <a href="https://www.youtube.com/watch?v=Ulp1Kimblg0" target="_blank">Swift</a></th>
Use font awesome swift icon.

2021-04-24 09:24 UTC, harikesh409 commented on index.html
> +        <th><i class="devicon-go-plain"></i>&nbsp; <a href="https://www.youtube.com/watch?v=YS4e4q9oBaU" target="_blank">Golang</a></th>
Keep the G icon or some other font awesome icon which might be related.

2021-04-24 09:24 UTC, harikesh409 commented on index.html
> +
remove the blank line.

2021-04-24 09:24 UTC, harikesh409 commented on index.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.11.0/devicon.min.css">
As suggested change to fontawesome icons and remove this additional icon pack.

2021-04-24 10:31 UTC, codebuzzer01 commented
@harikesh409  review it!

![Screenshot (225)](https://user-images.githubusercontent.com/52864294/115955757-34491380-a516-11eb-9514-51e3e37107a1.png)

2021-04-24 10:38 UTC, harikesh409 requested changes

2021-04-24 10:38 UTC, harikesh409 commented on index.html
> +
no need of empty line gap.

2021-04-24 10:38 UTC, harikesh409 commented on index.html
> +
no need of empty line gap.

2021-04-24 10:38 UTC, harikesh409 commented on index.html
> +
no need of empty line gap.

2021-04-24 10:38 UTC, harikesh409 commented on index.html
> +
no need of empty line gap.

2021-04-24 10:38 UTC, harikesh409 commented on index.html
> +
no need of empty line gap.

2021-04-24 11:31 UTC, harikesh409 approved these changes

2021-04-24 11:32 UTC, harikesh409 commented
@codebuzzer01 please resolve the merge conflicts.

2021-04-24 12:19 UTC, codebuzzer01 commented
@harikesh409  resolved !

2021-04-24 15:09 UTC, harikesh409 commented
> @harikesh409 resolved !

Still conflicts are there look into it.

2021-04-24 16:29 UTC, merged

2021-04-24 16:42 UTC, codebuzzer01 commented
Hey, @harikesh409  It should have a label of 'level' . You didn't assign it any.

2021-04-24 16:46 UTC, harikesh409 commented
> Hey, @harikesh409 It should have a label of 'level' . You didn't assign it any.

Updated the labels.