meta tags added
Algo-Phantoms/Algo-Phantoms-Frontend pull request #46
Opened 2021-03-03 07:06 UTC by maanpatel2492

I have added meta tags and description and SEO according to the lighthouse in more than 90%.
1) Please check the description and title once and give feedback accordingly.If there is any mistake I will rework on it.
2) In authors column in meta tags does I have to write all the team members name?

2021-03-27 07:45 UTC, harikesh409 requested changes

2021-03-27 07:45 UTC, harikesh409 commented on team.html
> +    <!doctype html>
remove the unnecessary space.

2021-03-27 07:45 UTC, harikesh409 commented on team.html
>  <head>
add the meta tags in `team.html` also.

2021-03-27 07:46 UTC, harikesh409 commented
@maanpatel2492 resolve the conflicts.

2021-03-27 10:31 UTC, maanpatel2492 commented on team.html
>  <head>
Okay

2021-04-10 12:45 UTC, ravikr126 commented
is this completed @maanpatel2492

2021-04-10 16:50 UTC, maanpatel2492 commented
> is this completed @maanpatel2492

yes it is.

2021-04-10 16:50 UTC, closed without merging