Added contact us page
Algo-Phantoms/Algo-Phantoms-Frontend pull request #460
Opened 2021-04-30 07:45 UTC by harshb02

# Description
Added the contact us page

Please include a summary of the change and which issue is fixed.
Fixes #51 

## List any dependencies that are required for this change 
NA

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
On my local host

## UI /UX changes
   Attach gif or screenshot for changes.
  
![screencapture-file-C-Users-HARSH-Desktop-Algo-Phantoms-Frontend-contact-html-2021-04-30-13_14_47](https://user-images.githubusercontent.com/58955446/116664423-1405d280-a9b6-11eb-9e0f-dfdeab55de03.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-14 10:18 UTC, ravikr126 commented
please remove conflicts then i will merge this pr @harshb02

2021-05-15 11:56 UTC, harshb02 commented
> please remove conflicts then i will merge this pr @harshb02

On it

2021-05-16 05:31 UTC, ravikr126 requested changes
remove the contact us section on the main page and change the navbar link to this page.

2021-05-17 08:30 UTC, harshb02 commented
> remove the contact us section on the main page and change the navbar link to this page.

Done with the changes you have requested and have resolved the conflicts also @ravikr126

2021-05-18 15:23 UTC, harikesh409 requested changes

2021-05-18 15:23 UTC, harikesh409 commented on contact.html
> +    <title>Algo Phantoms</title>
Change the title to Algo Phantoms | Contact

2021-05-18 15:23 UTC, harikesh409 commented on contact.html
> +                        <a class="nav-link  font-weight-bold nav-items" href="contact.html">Contact</a>
Make the link as # as it is the current page.

2021-05-18 15:23 UTC, harikesh409 commented on contact.html
> +                        <a class="nav-link font-weight-bold nav-items" href="#">Home <span
Make the link point to index.html

2021-05-18 15:23 UTC, harikesh409 commented on contact.html
> +                        <a class="nav-link font-weight-bold nav-items" href="#about">About</a>
Make the link point to index.html#about

2021-05-18 15:23 UTC, harikesh409 commented on contact.html
> +                            <div id="msgSubmit" class="h3 text-center hidden"></div>
What is the use of this div?

2021-05-18 15:23 UTC, harikesh409 commented on contact.html
> +                        <li>
Point it to index.html#about.

2021-05-18 15:23 UTC, harikesh409 commented on css/style.css
> -.top{
Why did you remove this?

2021-05-18 15:23 UTC, harikesh409 commented on css/style.css
> -@media only screen and (max-width: 600px) {
Why is this removed?

2021-05-24 11:47 UTC, harshb02 commented
Resolved the changes @harikesh409

2021-05-25 14:47 UTC, harikesh409 commented
> remove the contact us section on the main page and change the navbar link to this page.

This is not done.

2021-05-25 18:26 UTC, harshb02 commented
> > remove the contact us section on the main page and change the navbar link to this page.
> 
> This is not done.

now it is done @harikesh409

2021-05-28 15:53 UTC, harikesh409 approved these changes

2021-05-29 15:19 UTC, ravikr126 approved these changes

2021-05-29 15:19 UTC, merged