Fixed Image and data not being hidden on page flip in team.html in Firefox browser
Algo-Phantoms/Algo-Phantoms-Frontend pull request #475
Opened 2021-05-11 08:33 UTC by ishwari20

# Description

Fixed Image and data not being hidden on page flip in team.html in Firefox browser
Fixes #457

## List any dependencies that are required for this change 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
   
![Screenshot (197)](https://user-images.githubusercontent.com/56400099/117784806-90739d80-b261-11eb-80fa-e3b4a26fead5.png)

   - After :
![Screenshot (196)](https://user-images.githubusercontent.com/56400099/117784827-97021500-b261-11eb-84fa-ed330c5f9ba8.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-11 14:16 UTC, ravikr126 commented
this issue already done by someone .now it so correct in website @ishwari20

2021-05-11 14:20 UTC, ishwari20 commented
@ravikr126  But I forked the latest version and the issue was still there.

2021-05-11 14:25 UTC, ravikr126 commented
But I show there is no any error

2021-05-14 07:36 UTC, harikesh409 commented
> this issue already done by someone .now it so correct in website @ishwari20

The issue is still present for FireFox browser.

2021-05-14 07:39 UTC, harikesh409 requested changes

2021-05-14 07:39 UTC, harikesh409 commented on css/style.css
> +  transform: rotateX(0deg);
Only this line is new so just add this along with the other properties.

2021-05-14 07:39 UTC, harikesh409 commented on css/style.css
> +  position: absolute;
All these properties are already present.

2021-05-14 08:17 UTC, ishwari20 commented
@harikesh409 Done the changes. Please review

2021-05-14 08:18 UTC, harikesh409 approved these changes

2021-05-14 08:19 UTC, merged