404 error page added
Algo-Phantoms/Algo-Phantoms-Frontend pull request #494
Opened 2021-05-16 07:14 UTC by Ankita297

# Description
404 error page added
Fixes #166 

## List any dependencies that are required for this change 

## Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
    - After :
## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
![404 NOT FOUND - Google Chrome 16-05-2021 12_37_49](https://user-images.githubusercontent.com/67833077/118388755-ef5f5b00-b643-11eb-96a3-31031453f80e.png)
![404 NOT FOUND - Google Chrome 16-05-2021 12_37_57](https://user-images.githubusercontent.com/67833077/118388758-f4240f00-b643-11eb-9cee-a1a0c289ce3c.png)

https://user-images.githubusercontent.com/67833077/118388808-364d5080-b644-11eb-89d0-28de057e0cd2.mp4

2021-05-16 07:41 UTC, Ankita297 commented
@harikesh409 @ravikr126 Sir Please review my PR .

2021-05-16 08:08 UTC, harikesh409 requested changes
![image](https://user-images.githubusercontent.com/3501554/118390187-5fbdaa80-b64b-11eb-81b2-f2ca014492ca.png)

There are 2 scrollbars in certain resolutions and the Go Home button is in the white area instead of the coloured area as shown in your screenshots. Mostly the issue is due to  `.error-page>height:100vh` property.

2021-05-16 08:08 UTC, harikesh409 commented on css/style.css
> +.error-center {
Can be replaced with bootstrap `text-center` class.

2021-05-16 08:08 UTC, harikesh409 commented on 404.html
> +    <div class="error-center">
Can be replaced with `text-center` class and correct the indentation.

2021-05-16 13:32 UTC, Ankita297 commented
done the changes

2021-05-17 12:54 UTC, Ankita297 commented
@harikesh409 Sir Please review the PR.

2021-05-18 15:47 UTC, harikesh409 approved these changes

2021-05-18 15:47 UTC, merged