improved responsiveness
Algo-Phantoms/Algo-Phantoms-Frontend pull request #496
Opened 2021-05-16 14:43 UTC by Saumya-07

# Description

Summary of the change and which issue is fixed.
-I have improved responsiveness in the sharpen-skill section.
-I changed it from table to grid and added styling as required.

Fixed  #470 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
- Before :

https://user-images.githubusercontent.com/68998355/118401301-d2964800-b682-11eb-9e51-5a634747e570.mp4

- After :
    

https://user-images.githubusercontent.com/68998355/118401237-8945f880-b682-11eb-86aa-24aab093e2ee.mp4

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-18 15:28 UTC, harikesh409 requested changes
Change the class names `tr`, `td` and `table` to something more meaningful.

2021-05-18 15:28 UTC, harikesh409 commented on index.html
> +      <div class='tr'>
change the class name to something more meaningful.

2021-05-18 15:28 UTC, harikesh409 commented on index.html
> +    <div class="table">
change the class name to something more meaningful.

2021-05-18 15:28 UTC, harikesh409 commented on index.html
> +        <div class='td'><i class="fas fa-atom"></i>&nbsp; <a href="https://www.geeksforgeeks.org/data-structures/" target="_blank">Data Structures</a></div>
change the class name to something more meaningful.

2021-05-18 20:43 UTC, Saumya-07 commented
Added the required changes as mentioned @harikesh409

2021-05-22 13:49 UTC, harikesh409 approved these changes

2021-05-22 13:50 UTC, merged