Coding site
Algo-Phantoms/Algo-Phantoms-Frontend pull request #498
Opened 2021-05-17 11:10 UTC by Aarti002

@harikesh409 can u review this PR , i just want to know i'm going right or not.
Although some css parts are still needs to be done. And let me know if i need to add or remove something.
Thank you!

2021-05-18 16:00 UTC, harikesh409 requested changes
- [ ] Rename the file to `suggested-coding-site.html`
- [ ] The background is very odd, don't use images just use one of the theme colours.
- [ ] Remove `coding.jpg` file which is not being used.
- [ ] All external links should be opened in a new tab.
- [ ] Navbar is not the same as the home page.
- [ ] Under "10 Best Websites to Practice Coding Online" on the hover of the links the line is extending to the hole page, correct it.
- [ ] Resolve the merge conflicts.

2021-05-18 20:10 UTC, Aarti002 commented
@harikesh409 can u add level tag? and will make require changes .
Thank you!

2021-05-22 14:09 UTC, harikesh409 requested changes
![image](https://user-images.githubusercontent.com/3501554/119229367-50e86380-bb35-11eb-81c9-ae9febce8671.png)
- [ ] If we click on a link in `10 Best Websites to Practice Coding Online` section and hover on another link then both tooltips are being shown and are overlapping.
- [ ] Resolve the merge conflicts.

2021-05-22 14:09 UTC, harikesh409 commented on DSA.html
> +                             <a class="dropdown-item" href="booklist.htmls">Suggested Books</a>
The link is wrong it should be `booklist.html`

2021-05-22 14:09 UTC, harikesh409 commented on suggested_coding_site.html
> +            <section class="list--wrapper mt-5">
Instead of nesting this inside, move it outside of the outer section.

2021-05-22 14:09 UTC, harikesh409 commented on suggested_coding_site.html
> +            <h3>10 Best Websites to Practice Coding Online</h3>
Use h1 only as used above so the style is uniform.

2021-05-22 14:10 UTC, harikesh409 commented
> @harikesh409 can u add level tag? and will make require changes .
> Thank you!

While merging I will add all other labels.

2021-05-23 11:39 UTC, Aarti002 commented
@harikesh409 please review again i think everything is fine now.

2021-05-25 11:13 UTC, Aarti002 commented
@harikesh409 can you please review it as we don't have much time left and please let me know if everything is not fine?
Thank you!

2021-05-30 12:45 UTC, merged