skill section enhanced
Algo-Phantoms/Algo-Phantoms-Frontend pull request #505
Opened 2021-05-20 16:23 UTC by Ankita297

# Description

skill section enhanced
Fixes #476

## List any dependencies that are required for this change 

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] This change requires a documentation update

## How Has This Been Tested?

## UI /UX changes
   Attach gif or screenshot for changes.
   - Before :
    - After :
## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes

![Algo Phantoms - Google Chrome 20-05-2021 21_42_07](https://user-images.githubusercontent.com/67833077/119014495-a7c72f00-b9b5-11eb-9e1e-8c357494e129.png)
![Algo Phantoms - Google Chrome 20-05-2021 21_43_09](https://user-images.githubusercontent.com/67833077/119014499-a85fc580-b9b5-11eb-9155-558252b743bb.png)

![Algo Phantoms - Google Chrome 20-05-2021 21_39_31](https://user-images.githubusercontent.com/67833077/119014479-a4cc3e80-b9b5-11eb-987e-a230dae02cfa.png)

https://user-images.githubusercontent.com/67833077/119014558-b7467800-b9b5-11eb-82c2-63bb98e73bc2.mp4

2021-05-21 12:16 UTC, Ankita297 commented
@harikesh409 @ravikr126 Sir Please review my PR .

2021-05-21 12:18 UTC, ravikr126 approved these changes

2021-05-22 14:28 UTC, harikesh409 requested changes
There are few dead styles present in `style.css` like 
- .skills-section table
- .skills-section th:hover
- .skills-section th,td
- .skills-section tr:nth-child(odd) th
- .skills-section tr:nth-child(odd) th:hover
- .skills-section tr:nth-child(even) th:hover
Remove these properties.

2021-05-22 14:28 UTC, harikesh409 commented on index.html
>      <span class="span"></span>
Remove `<span class="span"></span>` this which is not necessary.

2021-05-22 14:43 UTC, Ankita297 commented
@harikesh409 Sir Please see now .

2021-05-22 14:43 UTC, harikesh409 approved these changes

2021-05-22 14:43 UTC, merged