added issue and pr templates
Algo-Phantoms/Algo-Phantoms-Frontend pull request #84
Opened 2021-03-10 06:37 UTC by Sloth-Panda

issue: #53

2021-03-11 19:22 UTC, Sloth-Panda commented
@Shruti3004 can you please review this pr and do add gssoc21 and level tags to both issue and pr

2021-03-15 20:51 UTC, harikesh409 requested changes

2021-03-15 20:51 UTC, harikesh409 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +labels: feature
change the label to `enhancement` as it is already being used in the repo

2021-03-17 12:46 UTC, Sloth-Panda commented
@harikesh409 I have updated it please check

2021-03-17 17:00 UTC, harikesh409 requested changes
Already pull_request_template is added throught #186 . Just remove that file then we can merge rest of the templates.

2021-03-18 10:15 UTC, Sloth-Panda commented
@harikesh409 has removed it u can check now

2021-03-18 10:21 UTC, merged